#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Trinity.Resource", IsApplication=true)]

namespace Trinity
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Premio1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Premio7 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Premio8 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int TrinityTeam160x160 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int TrinityTeam320x320 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int TrinityTeam40x40 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int TrinityTeam640x640 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int TrinityTeam72x72 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int TrinityTeam80x80 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002a
			public const int btnCadastro = 2131099690;
			
			// aapt resource value: 0x7f060016
			public const int btnConfirmarCadastro = 2131099670;
			
			// aapt resource value: 0x7f06003c
			public const int btnConfirmarTroca = 2131099708;
			
			// aapt resource value: 0x7f060024
			public const int btnEnviarLancamento = 2131099684;
			
			// aapt resource value: 0x7f06001c
			public const int btnEnviarRecuperarSenha = 2131099676;
			
			// aapt resource value: 0x7f06002e
			public const int btnLancarPagamentoMainMenu = 2131099694;
			
			// aapt resource value: 0x7f060029
			public const int btnLogin = 2131099689;
			
			// aapt resource value: 0x7f06002f
			public const int btnPremiosMainMenu = 2131099695;
			
			// aapt resource value: 0x7f06002b
			public const int btnRecuperarSenha = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int btnTimeLineMainMenu = 2131099693;
			
			// aapt resource value: 0x7f060031
			public const int btnTrocarItem1 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int btnTrocarItem2 = 2131099698;
			
			// aapt resource value: 0x7f060034
			public const int btnTrocarItem3 = 2131099700;
			
			// aapt resource value: 0x7f06003b
			public const int edtSenhaTroca = 2131099707;
			
			// aapt resource value: 0x7f060027
			public const int emailLogin = 2131099687;
			
			// aapt resource value: 0x7f060009
			public const int etxCPFCadastro = 2131099657;
			
			// aapt resource value: 0x7f060023
			public const int etxChaveNFCE = 2131099683;
			
			// aapt resource value: 0x7f060015
			public const int etxConfirmSenhaCadastro = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int etxConfirmTroca1 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int etxConfirmTroca2 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int etxConfirmTroca3 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int etxConfirmTroca4 = 2131099674;
			
			// aapt resource value: 0x7f060006
			public const int etxDataNascimentoCadatro = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int etxEmailCadastro = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int etxEmailRecuperarSenha = 2131099675;
			
			// aapt resource value: 0x7f060003
			public const int etxNomeCadastro = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int etxSenhaCadastro = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int etxTelefoneCadastro = 2131099660;
			
			// aapt resource value: 0x7f060030
			public const int imageView1 = 2131099696;
			
			// aapt resource value: 0x7f060026
			public const int imageView2 = 2131099686;
			
			// aapt resource value: 0x7f060033
			public const int imageView3 = 2131099699;
			
			// aapt resource value: 0x7f060038
			public const int imgTroca = 2131099704;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout3 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout4 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout5 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout6 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout7 = 2131099667;
			
			// aapt resource value: 0x7f060037
			public const int lsvFeed = 2131099703;
			
			// aapt resource value: 0x7f060025
			public const int lsvHistorico = 2131099685;
			
			// aapt resource value: 0x7f06001e
			public const int rdbAVista = 2131099678;
			
			// aapt resource value: 0x7f060022
			public const int rdbBoleto = 2131099682;
			
			// aapt resource value: 0x7f06001f
			public const int rdbCCVISA = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int rdbELO = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int rdbMASTERCARD = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int rdgFormaPagamentoPontos = 2131099677;
			
			// aapt resource value: 0x7f060028
			public const int senhaLogin = 2131099688;
			
			// aapt resource value: 0x7f060036
			public const int texEmailFeed = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int texNomeUsuarioFeed = 2131099701;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int textView2 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int textView3 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int textView4 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int textView5 = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int textView6 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int textView7 = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int toolbar = 2131099648;
			
			// aapt resource value: 0x7f06003a
			public const int txDescricaoPremioTroca = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int txNomePremioTroca = 2131099705;
			
			// aapt resource value: 0x7f06002c
			public const int txvOlaUsuarioMainMenu = 2131099692;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Cadastro = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConfirmTroca = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EsqSenha = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LancHistoPontos = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LoginScreem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Premio = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TimeLine = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Toolbar = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Troca = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
