-- --------------------------------------------------------
-- Servidor:                     commitsoft.com.br
-- Versão do servidor:           5.6.30 - MySQL Community Server (GPL)
-- OS do Servidor:               Linux
-- HeidiSQL Versão:              9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;



CREATE DATABASE IF NOT EXISTS `commitso_conductorhackathon` 
USE `commitso_conductorhackathon`;


CREATE TABLE IF NOT EXISTS `Feed` (
  `COD_PUBLICACAO` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_PUBLICACAO` datetime DEFAULT NULL,
  `DESCRICAO_FEED` varchar(1000) DEFAULT NULL,
  `FK_ID_USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`COD_PUBLICACAO`),
  KEY `FK_ID_USUARIO` (`FK_ID_USUARIO`),
  CONSTRAINT `FK_ID_USUARIO` FOREIGN KEY (`FK_ID_USUARIO`) REFERENCES `Usuario` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `Formas_Pagamentos` (
  `COD_PAGAMENTO` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICACAO_PAGAMENTO` varchar(50) NOT NULL,
  PRIMARY KEY (`COD_PAGAMENTO`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `Lacamentos` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FK_ID_USUARIO` int(11) DEFAULT NULL,
  `CHAVE_SEGURANCA` varchar(50) NOT NULL,
  `DATA_LACAMENTO` datetime DEFAULT NULL,
  `PONTOS_USUARIO` int(11) DEFAULT NULL,
  `VALOR_COMPRA` double NOT NULL,
  `STATUS` varchar(2) DEFAULT NULL,
  `TIPO_PAGAMENTO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;



CREATE TABLE IF NOT EXISTS `Mensagens` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_HORA_MENSAGEM` datetime DEFAULT NULL,
  `MENSAGEM` varchar(1000) DEFAULT NULL,
  `FK_ID_USUARIO_ORIGEM` int(11) DEFAULT NULL,
  `FK_ID_USUARIO_DESTINO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ID_USUARIO_ORIGEM` (`FK_ID_USUARIO_ORIGEM`),
  KEY `FK_ID_USUARIO_DESTINO` (`FK_ID_USUARIO_DESTINO`),
  CONSTRAINT `Mensagens_ibfk_1` FOREIGN KEY (`FK_ID_USUARIO_ORIGEM`) REFERENCES `Usuario` (`ID`),
  CONSTRAINT `Mensagens_ibfk_2` FOREIGN KEY (`FK_ID_USUARIO_DESTINO`) REFERENCES `Usuario` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `Premio` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_PREMIO` varchar(200) DEFAULT NULL,
  `DESCRICAO_PREMIO` varchar(300) DEFAULT NULL,
  `PRECO_PONTOS` double DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `Saldo_Usuario` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FK_ID_USUARIO` int(11) DEFAULT NULL,
  `SALDO_PONTOS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ID_USUARIO` (`FK_ID_USUARIO`),
  CONSTRAINT `Saldo_Usuario_ibfk_1` FOREIGN KEY (`FK_ID_USUARIO`) REFERENCES `Usuario` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CPF` varchar(11) NOT NULL,
  `NOME` varchar(50) NOT NULL,
  `DATA_NASCIMENTO` datetime NOT NULL,
  `TELEFONE` varchar(20) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `SENHA` varchar(16) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

